project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "An R Package for Dungeons & Dragons: `dndR`"
  favicon: inst/images/dndR_hex.png
  repo-url: https://github.com/njlyon0/dndR
  repo-actions: [issue]
  twitter-card: true
  navbar:
    background: primary
    right:
      - icon: github
        href: https://github.com/njlyon0/dndR
  sidebar:
    style: "docked"
    background: secondary
    search: true
    contents: 
      - href: index.qmd
        text: "Package Overview"
      - section: "For Everyone"
        contents: 
          - href: dice.qmd
            text: "Dice Rolling"
          - href: create-characters.qmd
            text: "Character Creation"
      - section: "For DMs"
        contents: 
          - href: encounter-balance.qmd
            text: "Balancing Encounters"
          - href: create-monsters.qmd
            text: "Monster Creation"
  page-footer:
    center: "Copyright 2022, Nicholas J Lyon"
    background: primary
  margin-footer: <img src="inst/images/dndR_hex.png" width = "40%" />

format:
  html:
    theme:
      light: minty
      dark: darkly
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false
