## ---------------------------------------------------- ##
# NPC Creator Function Upgrade
## ---------------------------------------------------- ##

# Billy (William) Mitchell (https://github.com/wj-mitchell) forked dndR and has been working on some new/upgraded functions
## The coolest / most-easily integratable (IMO) is his upgrades to the `npc_creator` function
## Working here on integrating his version with mine to get that improvement ASAP

## ------------------------------- ##
# Housekeeping ----
## ------------------------------- ##

# Load libraries
librarian::shelf(tidyverse, dndR)

# Clear environment
rm(list = ls()); gc()

## ------------------------------- ##
# Current Function ----
## ------------------------------- ##

# Invoke function to see output
old_out <- dndR::npc_creator(npc_count = 2)

# Check output
old_out
dplyr::glimpse(old_out)

## ------------------------------- ##
# Upgrade Dev Area ----
## ------------------------------- ##

npc_creator <- function(npc_count = 1){
  
  # NPC count must be a single number
  if(is.null(npc_count) || is.numeric(npc_count) != TRUE || length(npc_count) != 1)
    stop("'npc_count' must be specified as a single number")
  
  # Make sure count is an integer
  npc_count <- round(x = npc_count, digits = 0)
  
  # Pick a race
  npc_race <- sample(x = dndR::dnd_races(), size = npc_count, replace = TRUE)
  
  # Pick a career
  npc_role <- sample(x = c("acolyte", "adventurer", "ambassador", "anthropologist", "archaeologist", "artisan", "barber", "bounty hunter", "caravan driver", "caravan guard", "carpenter", "charlatan", "city watch", "criminal", "diplomat", "doctor", "farmer", "farrier", "entertainer", "gladiator", "hermit", "initiate", "inquisitor", "investigator", "knight", "mercenary", "merchant", "navigator", "noble", "outlander", "sage", "scholar", "smith", "soldier", "spy", "student of magic", "smuggler", "urchin", "veteran"),
                     size = npc_count, replace = TRUE)
  
  # Define some vectors of names
  ## Feminine first names ----
  fem_names <- c("Abia", "Abigail", "Abigala", "Abigayl", "Abjiga", "Abressa", 
                 "Abria", "Abrjia", "Abryia", "Abyiga", "Adressa", "Adria", "Adrjia", 
                 "Adryia", "Aebria", "Aedria", "Aelina", "Aelinea", "Aelisabeth", 
                 "Aeliya", "Aella", "Aelyssa", "Aemily", "Aemilya", "Aemma", "Aemy", 
                 "Aendrea", "Aeobreia", "Aeria", "Aeva", "Aevelyn", "Alaexa", 
                 "Aleksa", "Alessa", "Alessana", "Alexa", "Alia", "Alija", "Alina", 
                 "Alinea", "Alinia", "Alisann", "Alisea", "Alisia", "Alisja", 
                 "Aliss", "Alissa", "Alisya", "Alivia", "Alivya", "Aliya", "Allisann", 
                 "Allison", "Allysann", "Allyson", "Alova", "Alya", "Alyce", "Alyna", 
                 "Alys", "Alysann", "Alysea", "Alyss", "Alyssia", "Alyxa", "Amee", 
                 "Amelia", "Amelya", "Ami", "Amia", "Amilia", "Amilja", "Amja", 
                 "Amy", "Amya", "Andrea", "Andreja", "Andreya", "Anika", "Aodreia", 
                 "Aria", "Ariana", "Arianna", "Ariel", "Ariella", "Arielle", "Arja", 
                 "Arjana", "Arjel", "Arya", "Aryana", "Aryanna", "Aryel", "Aryell", 
                 "Aryella", "Ashlena", "Ashlene", "Ashlyne", "Aslena", "Asljena", 
                 "Aslyena", "Aubree", "Aubria", "Audree", "Audria", "Aurora", 
                 "Ava", "Avaery", "Avelia", "Avelina", "Averee", "Averra", "Avery", 
                 "Avia", "Avyrie", "Azalea", "Azelia", "Azlena", "Baella", "Bela", 
                 "Bella", "Belle", "Bera", "Betta", "Bree", "Breia", "Brianna", 
                 "Brinn", "Brinna", "Brjia", "Brocalina", "Brokalina", "Brooka", 
                 "Brooke", "Brooklinea", "Brooklyn", "Bruka", "Bryanna", "Bryia", 
                 "Brynn", "Brynna", "Caemila", "Caerlotta", "Calia", "Caliana", 
                 "Calla", "Camila", "Camilia", "Carlotta", "Catherina", "Cathryn", 
                 "Catrina", "Celine", "Celyne", "Chloe", "Chloeia", "Claira", 
                 "Claire", "Clara", "Clayra", "Clayre", "Cloe", "Cloey", "Cloia", 
                 "Dalia", "Dalilja", "Dalilya", "Dalyla", "Delia", "Delila", "Delyla", 
                 "Dree", "Dreia", "Drjia", "Dryia", "Elia", "Eliana", "Elisabet", 
                 "Elisybeth", "Eljana", "Ella", "Elli", "Ellia", "Ellie", "Ellja", 
                 "Ellya", "Elva", "Elyana", "Elyna", "Elyssa", "Ema", "Emili", 
                 "Emilia", "Emma", "Estelia", "Estella", "Eva", "Evylann", "Evylen", 
                 "Faline", "Falinia", "Falyne", "Fanna", "Fantina", "Feria", "Ferjia", 
                 "Ferra", "Feryia", "Genaesis", "Genaesys", "Genesia", "Genesys", 
                 "Gianesia", "Gianna", "Gina", "Ginna", "Grace", "Graece", "Graja", 
                 "Grassa", "Grassia", "Graya", "Grayce", "Grazia", "Haenna", "Halia", 
                 "Halie", "Halja", "Halya", "Hanna", "Hannah", "Harper", "Harperia", 
                 "Hazel", "Hazelia", "Hazyl", "Iasmina", "Illa", "Imaena", "Imina", 
                 "Isabel", "Isabella", "Iveljin", "Janna", "Jasmine", "Jasmyne", 
                 "Jazmina", "Jella", "Jemina", "Jenesa", "Jenessa", "Jianna", 
                 "Jocelina", "Joceline", "Jocelyn", "Jocelyne", "Joyce", "Kaeli", 
                 "Kaelia", "Kaelya", "Kaila", "Kalja", "Kalya", "Kamilia", "Kamilja", 
                 "Karlata", "Kathrine", "Kathrinn", "Kathryn", "Kathryne", "Katja", 
                 "Katrina", "Katya", "Kayla", "Kima", "Kimbera", "Klara", "Kloja", 
                 "Kloya", "Kym", "Kyma", "Kymber", "Laila", "Lailana", "Lana", 
                 "Lanja", "Lanna", "Lanya", "Layla", "Laylanna", "Lea", "Leah", 
                 "Leena", "Leia", "Leja", "Leya", "Liana", "Lilia", "Lilja", "Lily", 
                 "Lilya", "Lina", "Lippi", "Lisabeta", "Lisbeth", "Lona", "Loona", 
                 "Luna", "Lyana", "Lylia", "Lyly", "Lyna", "Lysbeth", "Lyssa", 
                 "Lyssie", "Madisinia", "Madisyn", "Madizinia", "Madjisa", "Madyisa", 
                 "Maedisa", "Maelania", "Maelya", "Maia", "Maja", "Maya", "Mea", 
                 "Melania", "Melanja", "Melany", "Melanya", "Mena", "Mia", "Mija", 
                 "Mila", "Milae", "Milannia", "Milia", "Milja", "Milly", "Milya", 
                 "Mina", "Miya", "Mjila", "Mya", "Myla", "Naome", "Naomi", "Natalia", 
                 "Nataliae", "Natalja", "Nataly", "Natalya", "Nathylie", "Natja", 
                 "Natta", "Natty", "Natya", "Natylie", "Nicola", "Nicolle", "Nikola", 
                 "Nomi", "Nomia", "Nycola", "Nycole", "Oiara", "Ojara", "Olifja", 
                 "Olifya", "Olivia", "Olivya", "Olyva", "Ondrea", "Oyara", "Paenelope", 
                 "Penelope", "Penny", "Pera", "Peria", "Perja", "Perya", "Pia", 
                 "Pinelopi", "Pinna", "Pippi", "Pynelope", "Riana", "Rianna", 
                 "Rilia", "Rilie", "Rjanna", "Rjila", "Rubi", "Rubia", "Ruby", 
                 "Ryanna", "Ryila", "Ryla", "Rylie", "Samaentha", "Samena", "Samentha", 
                 "Samitha", "Samitia", "Samitja", "Samitya", "Samytha", "Sara", 
                 "Sarah", "Sarra", "Savanna", "Savannia", "Scarlet", "Scarletta", 
                 "Scarlotta", "Selina", "Seline", "Selyne", "Sharla", "Sharlotta", 
                 "Sharlotte", "Skarlja", "Skarlya", "Sofi", "Sofia", "Soja", "Sophia", 
                 "Sophya", "Sosja", "Sosya", "Soya", "Stella", "Stelly", "Stylla", 
                 "Talea", "Talia", "Talya", "Tella", "Thalia", "Tylla", "Uzoia", 
                 "Vala", "Valea", "Valentina", "Valentyna", "Valeria", "Valerie", 
                 "Valerja", "Valerya", "Valia", "Valja", "Valya", "Vanna", "Victora", 
                 "Victoria", "Victorya", "Viktorja", "Viktorya", "Vila", "Vilettia", 
                 "Viola", "Violet", "Violetta", "Vittora", "Vittoria", "Vyla", 
                 "Ximena", "Yanna", "Yasmine", "Yella", "Yemina", "Yenesa", "Ysabel", 
                 "Yvelyn", "Zoe", "Zoea", "Zoeia", "Zoesia", "Zoey", "Zofia", 
                 "Zoia", "Zosia", "Zosy", "Zusia")
  
  ## Masculine first names ----
  masc_names <- c("Aaro", "Aaron", "Aarus", "Aaryn", "Abbos", "Abel", "Abelan", 
                  "Abelus", "Abrahm", "Abram", "Abramo", "Abramus", "Abyl", "Adam", 
                  "Adamo", "Adamos", "Adamus", "Adannius", "Adanno", "Adrian", 
                  "Adrio", "Adrios", "Adrjan", "Adros", "Adryan", "Adym", "Aedam", 
                  "Aedrian", "Aedrio", "Aedyn", "Aeli", "Aelijah", "Aemo", "Aendro", 
                  "Aendrus", "Aenglo", "Aenry", "Aethan", "Aethyn", "Aevan", "Aiden", 
                  "Aido", "Aidos", "Aidyn", "Aisaac", "Aisiah", "Aksel", "Alaen", 
                  "Alecks", "Aleks", "Aleksander", "Alennos", "Aleno", "Alessandro", 
                  "Alesso", "Alexander", "Alexandyr", "Alivyr", "Alix", "Alonnos", 
                  "Alonso", "Alvan", "Alver", "Alvero", "Alyn", "Alyx", "Andoran", 
                  "Andre", "Andrean", "Andrej", "Andrenas", "Andres", "Andrew", 
                  "Andrey", "Andro", "Androe", "Andros", "Andrus", "Angel", "Angelo", 
                  "Anglo", "Anglos", "Anglus", "Anjel", "Anthony", "Anton", "Antonio", 
                  "Antono", "Antony", "Antonyr", "Anyel", "Aro", "Aros", "Asten", 
                  "Astin", "Astinus", "Astono", "Astyn", "Athyn", "Axel", "Axelus", 
                  "Axlos", "Axyl", "Ayden", "Aydyn", "Bastien", "Bastio", "Bastyen", 
                  "Benemo", "Benemos", "Benjamin", "Benjamyn", "Benjamyr", "Benjen", 
                  "Benyen", "Bertus", "Braddeus", "Brado", "Bradyn", "Braendyn", 
                  "Brahm", "Brahn", "Braidyn", "Bram", "Brammos", "Bran", "Brandjen", 
                  "Brando", "Brandyn", "Brannos", "Branus", "Bridos", "Bronn", 
                  "Bronnos", "Bruno", "Bryan", "Brydus", "Bryn", "Brynden", "Bryne", 
                  "Bryus", "Caeleb", "Caelyb", "Caerlos", "Caertero", "Caleb", 
                  "Caliban", "Callos", "Calyb", "Cam", "Camero", "Camerus", "Cameryn", 
                  "Camryn", "Carliss", "Carlos", "Carlus", "Carolan", "Cartero", 
                  "Cartus", "Cartyr", "Cavo", "Cavos", "Chaerles", "Charlus", "Charly", 
                  "Chirles", "Christo", "Christophyr", "Chrystan", "Chrystian", 
                  "Chyrles", "Conner", "Connorus", "Connyr", "Conoro", "Cristeno", 
                  "Cristenos", "Cristian", "Cristofo", "Cristor", "Cristos", "Crystan", 
                  "Daemian", "Daenyel", "Daevo", "Dain", "Dale", "Dalian", "Dalio", 
                  "Damien", "Damino", "Damjin", "Dammos", "Damyan", "Damyin", "Damyn", 
                  "Dan", "Danello", "Danellos", "Daniel", "Danjel", "Dann", "Dannel", 
                  "Dannos", "Danny", "Dano", "Danyel", "Davek", "David", "Davios", 
                  "Davo", "Davyd", "Diegon", "Dominac", "Domino", "Domnac", "Domnik", 
                  "Domnos", "Dylaen", "Dylan", "Dylus", "Efan", "Efjan", "Efyan", 
                  "Egan", "Eli", "Elian", "Elias", "Eligio", "Elihios", "Elijah", 
                  "Elijan", "Elio", "Elius", "Eliyan", "Elje", "Ellios", "Ely", 
                  "Elyas", "Elye", "Elyjah", "Emannos", "Emanolo", "Emanus", "Emilanus", 
                  "Emilian", "Emiljan", "Emilyan", "Emmanus", "Emmon", "Emmyn", 
                  "Emynwell", "Enrico", "Enrikos", "Ephanos", "Eric", "Ericus", 
                  "Erik", "Eryc", "Eryck", "Eryk", "Esekio", "Esekios", "Esran", 
                  "Esro", "Etan", "Ethan", "Ethyn", "Evan", "Evanio", "Evanus", 
                  "Evyn", "Ewan", "Ezekio", "Ezekius", "Ezekyel", "Ezran", "Ezro", 
                  "Ezros", "Ezrus", "Gabrael", "Gabreal", "Gabreil", "Gabrilo", 
                  "Gabrios", "Gabrjel", "Gabryel", "Gaebriel", "Gael", "Gaeus", 
                  "Gaevyn", "Gafjen", "Gafyn", "Gail", "Galan", "Gallos", "Gavannos", 
                  "Gavano", "Gavin", "Gavyn", "Gayel", "Gayl", "Giaco", "Giacomo", 
                  "Giadeo", "Giasson", "Giassonos", "Gionato", "Gionatos", "Giorran", 
                  "Gioseno", "Giosenos", "Gioseppi", "Gioseppos", "Giosso", "Giovan", 
                  "Giulio", "Goshen", "Goshwa", "Graddos", "Graisen", "Grassio", 
                  "Grassos", "Grasyn", "Gray", "Graysen", "Graysus", "Guan", "Guliemo", 
                  "Guliemos", "Gwann", "Gwyllam", "Gwyllem", "Haddeo", "Haddeos", 
                  "Haddeus", "Hadeos", "Hadrian", "Hadsen", "Haesoe", "Haesus", 
                  "Haesys", "Hafjus", "Hafyus", "Han", "Hander", "Handros", "Handus", 
                  "Handyr", "Hano", "Hanos", "Hanro", "Hanros", "Hanto", "Hantos", 
                  "Hantus", "Harold", "Haroldus", "Haryld", "Hasselo", "Havio", 
                  "Havius", "Havy", "Helian", "Helius", "Heljan", "Helyan", "Henrik", 
                  "Henro", "Hessos", "Horace", "Horacio", "Horgus", "Horus", "Horyce", 
                  "Horys", "Hosea", "Hoseas", "Hosius", "Hossen", "Hosso", "Hossos", 
                  "Hudsen", "Hudsyn", "Hulios", "Huntyr", "Hynroe", "Hynrus", "Hynry", 
                  "Iacono", "Iaen", "Iago", "Iagos", "Iamos", "Iamus", "Ian", "Ianio", 
                  "Ianus", "Iasono", "Ibannos", "Iesso", "Ifjan", "Iono", "Isaac", 
                  "Isaak", "Isaias", "Isajas", "Isak", "Isamo", "Isamos", "Isiah", 
                  "Isimo", "Isimos", "Isjah", "Ivaen", "Ivan", "Ivano", "Jacob", 
                  "Jacoby", "Jacomo", "Jacus", "Jaden", "Jaeck", "Jaecob", "Jaecoby", 
                  "Jaeden", "Jaedyn", "Jaeremiah", "Jaeremy", "Jaesen", "Jak", 
                  "Jakob", "Jakomos", "Jakonos", "Jakos", "Jaks", "Jaksen", "Jamje", 
                  "Jamye", "Jan", "Jannos", "Jarl", "Jasjen", "Jason", "Jasonos", 
                  "Jasyn", "Jax", "Jaxon", "Jaxus", "Jaxyn", "Jayden", "Jaymes", 
                  "Jeraldo", "Jeremus", "Jesten", "Jestin", "Joathyn", "Joeseph", 
                  "Jofan", "Johan", "John", "Johnus", "Jonaeth", "Jonaf", "Jonath", 
                  "Jonathyn", "Jonn", "Jonus", "Jorden", "Jordus", "Jordyn", "Joren", 
                  "Jorros", "Josaeth", "Josaeus", "Josayah", "Josef", "Josephus", 
                  "Joseth", "Joshen", "Joshoe", "Josius", "Josjen", "Josyah", "Jovan", 
                  "Jovanus", "Jovos", "Julian", "Juljan", "Julyan", "Julyo", "Jyck", 
                  "Kaevin", "Kaliv", "Kamros", "Kamrus", "Kanus", "Karl", "Karlos", 
                  "Karlus", "Karolos", "Karros", "Kartus", "Kefjan", "Kefyan", 
                  "Kevan", "Kevin", "Kevyn", "Konoros", "Kristjan", "Kristofer", 
                  "Kristyan", "Laendus", "Laevi", "Lan", "Landen", "Lando", "Landon", 
                  "Landos", "Landyn", "Lebbios", "Lefi", "Lenus", "Leo", "Leon", 
                  "Leonaerdo", "Leonnos", "Leonus", "Leonyrdo", "Levi", "Levio", 
                  "Levius", "Levy", "Liam", "Liamo", "Liamos", "Lincon", "Lincono", 
                  "Linconos", "Linconus", "Lincus", "Linkus", "Linus", "Ljam", 
                  "Ljenard", "Ljonus", "Ljuk", "Logaen", "Logan", "Logus", "Lokan", 
                  "Louis", "Luc", "Lucae", "Lucaen", "Lucaes", "Lucan", "Lucas", 
                  "Lucios", "Lucius", "Lucjius", "Luco", "Lucoe", "Lucos", "Lucus", 
                  "Lucyus", "Lugo", "Luho", "Luhos", "Lukas", "Lukios", "Lyam", 
                  "Lyenard", "Lynard", "Lynardus", "Lyncon", "Lynkus", "Lyonus", 
                  "Lyuk", "Maeson", "Maetho", "Maks", "Maksimos", "Masnos", "Mason", 
                  "Masono", "Massimo", "Masyn", "Mateo", "Mateos", "Mathew", "Mathoe", 
                  "Matje", "Matjus", "Matos", "Matt", "Matteus", "Mattius", "Matto", 
                  "Mattos", "Matye", "Matyus", "Maximer", "Maximo", "Maximus", 
                  "Maxus", "Maxymer", "Michael", "Miglan", "Miglos", "Miglus", 
                  "Miguel", "Miguelos", "Migwell", "Miliano", "Milio", "Milyannos", 
                  "Mither", "Mithrus", "Mitje", "Mitro", "Mitros", "Mitye", "Mychael", 
                  "Mygwell", "Mykael", "Mythro", "Naemo", "Naethyn", "Naethynel", 
                  "Natan", "Natannos", "Nateo", "Nathan", "Nathanus", "Nathanyel", 
                  "Nathyn", "Nathynel", "Natjan", "Natjanus", "Natos", "Natyan", 
                  "Natyanus", "Nicholaes", "Nicholus", "Nicholys", "Nicolo", "Nicolus", 
                  "Nicos", "Nik", "Nikolas", "Noam", "Nolan", "Nolannos", "Nolano", 
                  "Nolanus", "Nolen", "Nolyn", "Nom", "Nycholas", "Oewyn", "Ojin", 
                  "Olivus", "Olivyr", "Olliver", "Olver", "Oscar", "Oscaro", "Oscarus", 
                  "Osco", "Oscoe", "Oscus", "Oskar", "Oskos", "Otio", "Ottios", 
                  "Owen", "Owyn", "Raen", "Remmos", "Remo", "Remus", "Rian", "Riano", 
                  "Rianos", "Riddros", "Ridero", "Riderus", "Ridyr", "Rjan", "Robb", 
                  "Robbos", "Robero", "Robertus", "Robett", "Robjet", "Robyet", 
                  "Roman", "Romannos", "Romanus", "Romen", "Romyn", "Ryan", "Ryder", 
                  "Ryderus", "Ryn", "Saccaros", "Saccoro", "Saemuel", "Sammen", 
                  "Samos", "Samual", "Samuel", "Samwell", "Santaegus", "Santegus", 
                  "Santjeg", "Santo", "Santos", "Santus", "Santyeg", "Sebasten", 
                  "Sebastio", "Sebastjan", "Sebastos", "Sebastyan", "Sekjus", "Sekyus", 
                  "Siahus", "Skarje", "Skarye", "Stonnos", "Sybasten", "Taegus", 
                  "Tago", "Tagos", "Tagus", "Teddus", "Teodoro", "Teodus", "Thaeodore", 
                  "Thedoras", "Theodor", "Theodorus", "Theodus", "Thom", "Thomas", 
                  "Thomys", "Tiago", "Tiagon", "Tilo", "Tiloros", "Tilus", "Tilyr", 
                  "Tofer", "Tomm", "Tommas", "Tommos", "Tommus", "Tomo", "Tomus", 
                  "Tophyr", "Tornos", "Ty", "Tyago", "Tyego", "Tylor", "Tylus", 
                  "Uenio", "Unnos", "Uwyn", "Victor", "Victoran", "Victorus", "Victyr", 
                  "Viktor", "Viktus", "Vincenso", "Vincent", "Vincentus", "Vincenzo", 
                  "Vincynt", "Vinkus", "Vinnos", "Vintus", "Vyctor", "Vynce", "Vyncent", 
                  "Vyntus", "Wann", "Wanny", "Wilhelm", "Willam", "Willem", "Wjat", 
                  "Wyaett", "Wyat", "Wytt", "Wyttus", "Xander", "Xandyr", "Xavios", 
                  "Xavius", "Xavy", "Xavyer", "Yaden", "Yago", "Yak", "Yakob", 
                  "Yaks", "Yaksen", "Yan", "Yarl", "Yesten", "Yestin", "Yfan", 
                  "Ygan", "Yofan", "Yohan", "Yonaf", "Yonnos", "Yoren", "Yosef", 
                  "Yoshen", "Yosyen", "Ysaac", "Ysaiah", "Ysak", "Ysiah", "Yulian", 
                  "Yvan", "Yzra", "Zachaery", "Zachar", "Zacharus", "Zeckus", "Zeek", 
                  "Zeke")
  
            # Surnames -----
  sur_names <- c(c("Ackes", "Ailes", "Aler", "Alley", "Allie", "Altarside", "Altarworthy", 
                   "Anchor", "Anker", "Ankor", "Anvill", "Anvilson", "Appler", "Appleyard", 
                   "Applin", "Arch", "Archer", "Archmaker", "Ax", "Bailey", "Bakeler", 
                   "Baker", "Ballast", "Bankes", "Banks", "Banner", "Bannerman", 
                   "Barnard", "Barnes", "Barr", "Barre", "Basket", "Baskett", "Bay", 
                   "Bayer", "Bayers", "Bayes", "Beach", "Beacher", "Beacon", "Beecon", 
                   "Beeken", "Bell", "Bellows", "Bend", "Benderman", "Berg", "Berger", 
                   "Berriman", "Berry", "Berryland", "Bigg", "Biggs", "Bilder", 
                   "Bilds", "Billie", "Billy", "Birch", "Bird", "Birdett", "Black", 
                   "Blackfly", "Blackiron", "Blackscale", "Blacksky", "Blacktide", 
                   "Blackwater", "Bloom", "Bloomland", "Blow", "Blue", "Bluffclimber", 
                   "Bluffe", "Bobbin", "Bogg", "Boggs", "Bogs", "Boiles", "Bolt", 
                   "Bolte", "Bolter", "Bones", "Bootes", "Boots", "Boulder", "Bowman", 
                   "Boyle", "Boyles", "Branch", "Brand", "Brewer", "Brewster", "Bricker", 
                   "Brickhouse", "Brickman", "Bricks", "Bridges", "Brigg", "Briggs", 
                   "Bright", "Brightstar", "Broiles", "Brownard", "Browne", "Broyler", 
                   "Broyles", "Brush", "Brushfire", "Brycks", "Buck", "Builder", 
                   "Bulder", "Bull", "Bullyard", "Burg", "Burger", "Burgh", "Burgher", 
                   "Burns", "Butcher", "Butchett", "Button", "Buttonworth", "Buzzfly", 
                   "Byggs", "Byrch", "Byrd", "Byrdman", "Camp", "Campman", "Candler", 
                   "Capers", "Capman", "Capp", "Carpenter", "Carrier", "Carryer", 
                   "Carter", "Carton", "Cartwright", "Cash", "Cast", "Castaway", 
                   "Caster", "Chandler", "Chaplain", "Chaplin", "Chestnut", "Church", 
                   "Churchside", "Claimer", "Clay", "Claymer", "Clayms", "Coaldigger", 
                   "Coaler", "Coalman", "Coates", "Cole", "Coledegger", "Coleman", 
                   "Coler", "Colt", "Colter", "Condor", "Condorman", "Cook", "Cooper", 
                   "Copper", "Coppers", "Cotton", "Cottonseed", "Court", "Crab", 
                   "Crabb", "Crabber", "Crabman", "Crafter", "Cragg", "Cragman", 
                   "Craw", "Cray", "Crest", "Crickets", "Cricketts", "Croppe", "Curry", 
                   "Curser", "Darkbrother", "Darker", "Darko", "Darkstar", "Darkwater", 
                   "Darryman", "Dayes", "Days", "Deacon", "Deals", "Decker", "Decks", 
                   "Deecon", "Deeken", "Deel", "Deelaker", "Deelman. Diamond", "Deels", 
                   "Deere", "Deerman", "Derry", "Dice", "Digger", "Diggett", "Diggman", 
                   "Diggs", "Doe", "Doones", "Doons", "Dougher", "Dougherman", "Draco", 
                   "Dragon", "Dragonfly", "Dragonhoard", "Dragonhord", "Drake", 
                   "Dreamer", "Dredge", "Dredger", "Dreemer", "Dreems", "Driver", 
                   "Dryver", "Dunes", "Dunne", "Dunneman", "Dyce", "Dycen", "Dye", 
                   "Dyer", "Dyerson", "Dyeworth", "Dyson", "Ealer", "Eales", "Eddy", 
                   "Eeler", "Eeles", "Farmor", "Farrier", "Feller", "Felter", "Felterman", 
                   "Ferrimen", "Ferry", "Ferryman", "Fielder", "Fieldman", "Fields", 
                   "Fisher", "Fishman", "Flag", "Flagg", "Flats", "Fletcher", "Fletchett", 
                   "Flowers", "Foote", "Forester", "Forgeman", "Forger", "Forrest", 
                   "Forrester", "Fox", "Foxx", "Frey", "Frogg", "Frogman", "Frost", 
                   "Fry", "Fryman", "Furrman", "Furrs", "Gardener", "Gardiner", 
                   "Gardner", "Garr", "Glasier", "Glass", "Glazier", "Glover", "Gold", 
                   "Golden", "Goldman", "Goldsmith", "Goodbrother", "Goodman", "Gray", 
                   "Graysky", "Green", "Greene", "Greenscale", "Greentide", "Greentree", 
                   "Greenwater", "Greenyard", "Grey", "Greyscale", "Greysteel", 
                   "Grillett", "Grills", "Grove", "Groveland", "Groves", "Hall", 
                   "Hammer", "Hammett", "Handler", "Hardison", "Hardland", "Hardy", 
                   "Harland", "Harper", "Hatchet", "Hatson", "Hatter", "Hattiman", 
                   "Hatty", "Haul", "Hayes", "Hayward", "Heap", "Heckes", "Hecks", 
                   "Heights", "Helms", "Helmsman", "Hemings", "Hemmings", "Hemson", 
                   "Henkeeper", "Hennerman", "Hex", "Hides", "Highland", "Hightower", 
                   "Hights", "Hill", "Hillclimber", "Hills", "Hites", "Hoar", "Hoard", 
                   "Hoardigger", "Holiday", "Holier", "Holliday", "Hollier", "Hollison", 
                   "Holly", "Holyday", "Hood", "Hook", "Hooke", "Hopper", "Hord", 
                   "Hordegger", "House", "Hunter", "Huntsman", "Hurd", "Hyde", "Hydes", 
                   "Hylls", "Hylltopper", "Hytes", "Ice", "Icecutter", "Iceland", 
                   "Icewind", "Iles", "Inman", "Innes", "Innman", "Ironhoof", "Irons", 
                   "Ironshoe", "Ironsmith", "Isles", "Jack", "Jewels", "Jewls", 
                   "Jules", "Kabbage", "Kast", "Kearse", "Kerse", "Kerser", "Kettle", 
                   "Kettleblack", "Kettleman", "Kidd", "Kipman", "Kipper", "Kipson", 
                   "Kneadler", "Kneadman", "Knight", "Kopperfield", "Lain", "Laine", 
                   "Lander", "Lane", "Leathers", "Lender", "Lenderman", "Lethers", 
                   "Lodge", "Lodges", "Longdark", "Longnight", "Lynder", "Mair", 
                   "Maker", "March", "Marcher", "Mares", "Marks", "Marsh", "Masen", 
                   "Mason", "Mast", "Masyn", "May", "Mayfly", "Mayr", "Meadows", 
                   "Mercer", "Milk", "Millard", "Miller", "Mills", "Miner", "Minor", 
                   "Mole", "Moler", "Moller", "Molsen", "Molson", "Money", "Monk", 
                   "Monnee", "Monny", "Moon", "Moss", "Mosstree", "Munk", "Munnee", 
                   "Munny", "Myner", "Mynor", "Needleman", "Needler", "Needleworth", 
                   "Neeps", "Norland", "Norman", "North", "Northland", "Northman", 
                   "Northstar", "Nun", "Nunn", "Nutt", "Oakes", "Oaks", "Oars", 
                   "Oates", "Oredigger", "Ores", "Orr", "Orrdegger", "Orrs", "Orrsen", 
                   "Orson", "Overfield", "Overwise", "Oxbow", "Palewine", "Palmer", 
                   "Palms", "Pan", "Pannerman", "Panning", "Pans", "Park", "Parks", 
                   "Peabody", "Peaks", "Pearman", "Peartree", "Pease", "Peeks", 
                   "Peers", "Pepper", "Peppers", "Pickens", "Pickes", "Picketts", 
                   "Pickleman", "Pickler", "Pickles", "Pickman", "Piemaker", "Pieman", 
                   "Piers", "Pike", "Pikeclimber", "Pikeman", "Pikes", "Pine", "Pines", 
                   "Pitch", "Pix", "Plaza", "Ploughman", "Plowman", "Poisonweed", 
                   "Poisonwood", "Poleman", "Pollard", "Pollin", "Polliwog", "Polly", 
                   "Pollywog", "Polman", "Porter", "Porter Redtide", "Pott", "Pottaker", 
                   "Potter", "Potts", "Pound", "Poundstone", "Powers", "Preacher", 
                   "Preecher", "Preest", "Priest", "Pyckes", "Pyke", "Pykeman", 
                   "Pykes", "Pyketopper", "Pyne", "Pynes", "Pytch", "Quarrier", 
                   "Quarryman", "Quick", "Quicke", "Rafman", "Raftman", "Rainard", 
                   "Raines", "Rains", "Ratman", "Ratt", "Raynes", "Redd", "Redflats", 
                   "Redmoon", "Redscale", "Redwine", "Reed", "Reede", "Reedy", "Reel", 
                   "Reelings", "Reines", "Reins", "Reynes", "Reyns", "Rhoads", "Rhodes", 
                   "Rich", "Riches", "Richett", "Richman", "Rider", "Ridge", "Ridgeclimber", 
                   "Ridgetopper", "Riggett", "Riggs", "River", "Rivers", "Roades", 
                   "Roasterman", "Rock", "Rocker", "Rockman", "Rockridge", "Roof", 
                   "Roofe", "Root", "Roote", "Rotman", "Rotten", "Rutland", "Ryde", 
                   "Ryder", "Saddler", "Saffron", "Sage", "Sageworthy", "Sailer", 
                   "Sailor", "Saint", "Salmon", "Salt", "Salter", "Saltman", "Sandflats", 
                   "Sandman", "Sands", "Sawyer", "Sayler", "Saylor", "Scales", "Schippman", 
                   "Schipps", "Scholyr", "School", "Seabreeze", "Seales", "Seals", 
                   "Seaman", "Seams", "Seasalt", "Season", "Seeman", "Seems", "Seemworth", 
                   "Shaka", "Shearer", "Shears", "Sheerer", "Sheers", "Shell", "Sheller", 
                   "Shelley", "Shellman", "Shellmound", "Shepard", "Shepyrd", "Shields", 
                   "Shieldson", "Shine", "Shipman", "Shipps", "Ships", "Shoals", 
                   "Shock", "Shocker", "Shoefly", "Shoemaker", "Shore", "Shoreman", 
                   "Shwimmer", "Silver", "Silverman", "Silvermoon", "Simmerman", 
                   "Simms", "Singer", "Skeeter", "Skelton", "Skeltyn", "Skito", 
                   "Skolar", "Skool", "Slagg", "Slagman", "Slaughter", "Small", 
                   "Smalls", "Smart", "Smith", "Smittens", "Smitts", "Smitty", "Smoke", 
                   "Smoker", "Smyth", "Smythett", "Snailman", "Snails", "Snow", 
                   "Snowes", "Soward", "Sower", "Spade", "Spader Springs", "Spanner", 
                   "Spears", "Speers", "Speller", "Spelling", "Spiceman", "Spicer", 
                   "Springer", "Springs", "Stairs", "Stall", "Staller", "Stallman", 
                   "Stalls", "Stallworth", "Star", "Starr", "Steel", "Steele", "Steelman", 
                   "Stern", "Sterne", "Stillwater", "Stitches", "Stitchworth", "Stone", 
                   "Stoneflats", "Stoneman", "Storm", "Storms", "Streams", "Streems", 
                   "Street", "Streets", "Strider", "Stryder", "Summers", "Sunn", 
                   "Sunner", "Swift", "Swimmer", "Swords", "Swordson", "Swyft", 
                   "Swymmer", "Sylver", "Tailor", "Tanner", "Tannerman", "Tar", 
                   "Tarr", "Tate", "Taylor", "Teech", "Teeches", "Theery", "Thick", 
                   "Thicke", "Thredd", "Threddaker", "Threddler", "Threddman", "Thresh", 
                   "Threshett", "Thyme", "Tidewater", "Tillman", "Tine", "Tinker", 
                   "Tinman", "Tinn", "Towers", "Townes", "Towney", "Towns", "Townsend", 
                   "Towny", "Trainer", "Trainor", "Trout", "Tudor", "Tuggs", "Tugman", 
                   "Tutor", "Tyne", "Tynn", "Underhill", "Underman", "Underwood", 
                   "Vicker", "Vickers", "Vikars", "Vinaker Winaker", "Vines", "Vinter", 
                   "Vintner", "Vista", "Vykar", "Wackes", "Wahl", "Wahls", "Wain", 
                   "Wainwright", "Walker", "Wall", "Waller", "Walls", "Ware", "Waterman", 
                   "Waters", "Watters", "Wax", "Waxman", "Wayn", "Wayne", "Waynwright", 
                   "Weaver", "Weever", "Whitard", "White", "Whitesky", "Whitewater", 
                   "Whitley", "Whittaker", "Whyte", "Wineman", "Winnows", "Winter", 
                   "Wintermoon", "Winters", "Wise", "Wood", "Woode", "Wooden", "Woodhouse", 
                   "Woods", "Woodyn", "Wool", "Woolard", "Woolworth", "Worms", "Worthy", 
                   "Wurms", "Wynters", "Yardley", "Yardly", "Yards", "Ycecutter", 
                   "Yceland", "Ycewind", "Yrons", "Zapp"))
  
  # Assemble into named vector
  npc_info <- data.frame("race" = npc_race, 
                         "job" = npc_role)
  
  # Return the data.frame
  return(npc_info) }



# End ----
