## ---------------------------------------------------- ##
# NPC Creator Function Upgrade
## ---------------------------------------------------- ##

# Billy (William) Mitchell (https://github.com/wj-mitchell) forked dndR and has been working on some new/upgraded functions
## The coolest / most-easily integratable (IMO) is his upgrades to the `npc_creator` function
## Working here on integrating his version with mine to get that improvement ASAP

## ------------------------------- ##
# Housekeeping ----
## ------------------------------- ##

# Load libraries
librarian::shelf(tidyverse, dndR)

# Clear environment
rm(list = ls()); gc()

## ------------------------------- ##
# Current Function ----
## ------------------------------- ##

# Invoke function to see output
old_out <- dndR::npc_creator(npc_count = 2)

# Check output
old_out
dplyr::glimpse(old_out)

## ------------------------------- ##
# Upgrade Dev Area ----
## ------------------------------- ##

npc_creator <- function(npc_count = 1){
  
  # NPC count must be a single number
  if(is.null(npc_count) || is.numeric(npc_count) != TRUE || length(npc_count) != 1)
    stop("'npc_count' must be specified as a single number")
  
  # Define some vectors of names
  ## Feminine first names ----
  fem_names <- c("Abia", "Abigail", "Abigala", "Abigayl", "Abjiga", "Abressa", 
    "Abria", "Abrjia", "Abryia", "Abyiga", "Adressa", "Adria", "Adrjia", 
    "Adryia", "Aebria", "Aedria", "Aelina", "Aelinea", "Aelisabeth", 
    "Aeliya", "Aella", "Aelyssa", "Aemily", "Aemilya", "Aemma", "Aemy", 
    "Aendrea", "Aeobreia", "Aeria", "Aeva", "Aevelyn", "Alaexa", 
    "Aleksa", "Alessa", "Alessana", "Alexa", "Alia", "Alija", "Alina", 
    "Alinea", "Alinia", "Alisann", "Alisea", "Alisia", "Alisja", 
    "Aliss", "Alissa", "Alisya", "Alivia", "Alivya", "Aliya", "Allisann", 
    "Allison", "Allysann", "Allyson", "Alova", "Alya", "Alyce", "Alyna", 
    "Alys", "Alysann", "Alysea", "Alyss", "Alyssia", "Alyxa", "Amee", 
    "Amelia", "Amelya", "Ami", "Amia", "Amilia", "Amilja", "Amja", 
    "Amy", "Amya", "Andrea", "Andreja", "Andreya", "Anika", "Aodreia", 
    "Aria", "Ariana", "Arianna", "Ariel", "Ariella", "Arielle", "Arja", 
    "Arjana", "Arjel", "Arya", "Aryana", "Aryanna", "Aryel", "Aryell", 
    "Aryella", "Ashlena", "Ashlene", "Ashlyne", "Aslena", "Asljena", 
    "Aslyena", "Aubree", "Aubria", "Audree", "Audria", "Aurora", 
    "Ava", "Avaery", "Avelia", "Avelina", "Averee", "Averra", "Avery", 
    "Avia", "Avyrie", "Azalea", "Azelia", "Azlena", "Baella", "Bela", 
    "Bella", "Belle", "Bera", "Betta", "Bree", "Breia", "Brianna", 
    "Brinn", "Brinna", "Brjia", "Brocalina", "Brokalina", "Brooka", 
    "Brooke", "Brooklinea", "Brooklyn", "Bruka", "Bryanna", "Bryia", 
    "Brynn", "Brynna", "Caemila", "Caerlotta", "Calia", "Caliana", 
    "Calla", "Camila", "Camilia", "Carlotta", "Catherina", "Cathryn", 
    "Catrina", "Celine", "Celyne", "Chloe", "Chloeia", "Claira", 
    "Claire", "Clara", "Clayra", "Clayre", "Cloe", "Cloey", "Cloia", 
    "Dalia", "Dalilja", "Dalilya", "Dalyla", "Delia", "Delila", "Delyla", 
    "Dree", "Dreia", "Drjia", "Dryia", "Elia", "Eliana", "Elisabet", 
    "Elisybeth", "Eljana", "Ella", "Elli", "Ellia", "Ellie", "Ellja", 
    "Ellya", "Elva", "Elyana", "Elyna", "Elyssa", "Ema", "Emili", 
    "Emilia", "Emma", "Estelia", "Estella", "Eva", "Evylann", "Evylen", 
    "Faline", "Falinia", "Falyne", "Fanna", "Fantina", "Feria", "Ferjia", 
    "Ferra", "Feryia", "Genaesis", "Genaesys", "Genesia", "Genesys", 
    "Gianesia", "Gianna", "Gina", "Ginna", "Grace", "Graece", "Graja", 
    "Grassa", "Grassia", "Graya", "Grayce", "Grazia", "Haenna", "Halia", 
    "Halie", "Halja", "Halya", "Hanna", "Hannah", "Harper", "Harperia", 
    "Hazel", "Hazelia", "Hazyl", "Iasmina", "Illa", "Imaena", "Imina", 
    "Isabel", "Isabella", "Iveljin", "Janna", "Jasmine", "Jasmyne", 
    "Jazmina", "Jella", "Jemina", "Jenesa", "Jenessa", "Jianna", 
    "Jocelina", "Joceline", "Jocelyn", "Jocelyne", "Joyce", "Kaeli", 
    "Kaelia", "Kaelya", "Kaila", "Kalja", "Kalya", "Kamilia", "Kamilja", 
    "Karlata", "Kathrine", "Kathrinn", "Kathryn", "Kathryne", "Katja", 
    "Katrina", "Katya", "Kayla", "Kima", "Kimbera", "Klara", "Kloja", 
    "Kloya", "Kym", "Kyma", "Kymber", "Laila", "Lailana", "Lana", 
    "Lanja", "Lanna", "Lanya", "Layla", "Laylanna", "Lea", "Leah", 
    "Leena", "Leia", "Leja", "Leya", "Liana", "Lilia", "Lilja", "Lily", 
    "Lilya", "Lina", "Lippi", "Lisabeta", "Lisbeth", "Lona", "Loona", 
    "Luna", "Lyana", "Lylia", "Lyly", "Lyna", "Lysbeth", "Lyssa", 
    "Lyssie", "Madisinia", "Madisyn", "Madizinia", "Madjisa", "Madyisa", 
    "Maedisa", "Maelania", "Maelya", "Maia", "Maja", "Maya", "Mea", 
    "Melania", "Melanja", "Melany", "Melanya", "Mena", "Mia", "Mija", 
    "Mila", "Milae", "Milannia", "Milia", "Milja", "Milly", "Milya", 
    "Mina", "Miya", "Mjila", "Mya", "Myla", "Naome", "Naomi", "Natalia", 
    "Nataliae", "Natalja", "Nataly", "Natalya", "Nathylie", "Natja", 
    "Natta", "Natty", "Natya", "Natylie", "Nicola", "Nicolle", "Nikola", 
    "Nomi", "Nomia", "Nycola", "Nycole", "Oiara", "Ojara", "Olifja", 
    "Olifya", "Olivia", "Olivya", "Olyva", "Ondrea", "Oyara", "Paenelope", 
    "Penelope", "Penny", "Pera", "Peria", "Perja", "Perya", "Pia", 
    "Pinelopi", "Pinna", "Pippi", "Pynelope", "Riana", "Rianna", 
    "Rilia", "Rilie", "Rjanna", "Rjila", "Rubi", "Rubia", "Ruby", 
    "Ryanna", "Ryila", "Ryla", "Rylie", "Samaentha", "Samena", "Samentha", 
    "Samitha", "Samitia", "Samitja", "Samitya", "Samytha", "Sara", 
    "Sarah", "Sarra", "Savanna", "Savannia", "Scarlet", "Scarletta", 
    "Scarlotta", "Selina", "Seline", "Selyne", "Sharla", "Sharlotta", 
    "Sharlotte", "Skarlja", "Skarlya", "Sofi", "Sofia", "Soja", "Sophia", 
    "Sophya", "Sosja", "Sosya", "Soya", "Stella", "Stelly", "Stylla", 
    "Talea", "Talia", "Talya", "Tella", "Thalia", "Tylla", "Uzoia", 
    "Vala", "Valea", "Valentina", "Valentyna", "Valeria", "Valerie", 
    "Valerja", "Valerya", "Valia", "Valja", "Valya", "Vanna", "Victora", 
    "Victoria", "Victorya", "Viktorja", "Viktorya", "Vila", "Vilettia", 
    "Viola", "Violet", "Violetta", "Vittora", "Vittoria", "Vyla", 
    "Ximena", "Yanna", "Yasmine", "Yella", "Yemina", "Yenesa", "Ysabel", 
    "Yvelyn", "Zoe", "Zoea", "Zoeia", "Zoesia", "Zoey", "Zofia", 
    "Zoia", "Zosia", "Zosy", "Zusia")
  
  
  
  fem1 <- c("Abigayl", "Aebria", "Aeobreia", "Breia", "Aedria", "Aodreia", "Dreia", "Aeliya", "Aliya", "Aella", "Aemilya", "Aemma", "Aemy", "Amy", "Ami", "Aeria", "Arya", "Aeva", "Aevelyn", "Evylann", "Alaexa", "Alyxa", "Alina", "Aelina", "Aelinea", "Allisann", "Allysann", "Alyce", "Alys", "Alysea", "Alyssia", "Aelyssa", "Amelya", "Maelya", "Andreya", "Aendrea", "Arianna", "Aryanna", "Arielle", "Aryell", "Ariella", "Ashlena", "Aurora", "Avaery", "Avyrie", "Bella", "Baella", "Brooklinea", "Bryanna", "Brynna", "Brinna", "Caemila", "Chloe", "Chloeia", "Claira", "Clayre", "Clayra", "Delyla", "Dalyla", "Elisybeth", "Aelisabeth", "Ellia", "Ellya", "Elyana", "Eliana", "Eva", "Falyne", "Genaesis", "Genaesys", "Gianna", "Jianna", "Janna", "Graece", "Grassa", "Haenna", "Hanna", "Halya", "Harperia", "Peria", "Hazyl", "Hazel", "Jasmyne", "Jasmine", "Jocelyne", "Joceline", "Celine", "Kaelia", "Kaelya", "Kathryne", "Kathrine", "Kayla", "Kaila", "Kymber", "Kimbera", "Layla", "Laylanna", "Leia", "Leya", "Leah", "Lilia", "Lylia", "Luna", "Maedisa", "Maelania", "Melania", "Maya", "Mya", "Myla", "Milae", "Naomi", "Naome", "Natalya", "Talya", "Nathylie", "Nataliae", "Thalia", "Nicola", "Nikola", "Nycola", "Olivya", "Alivya", "Penelope", "Paenelope", "Pynelope", "Rianna", "Ryanna", "Ruby", "Ryla", "Samaentha", "Samytha", "Sara", "Sarah", "Savannia", "Scarletta", "Sharlotta", "Caerlotta", "Sophya", "Stella", "Stylla", "Valentyna", "Valerya", "Valeria", "Valia", "Valea", "Victorya", "Vilettia", "Ximena", "Imaena", "Ysabel", "Zoe", "Zoeia", "Zoea", "Zoesia")
  fem2 <- c("Abigail", "Aemily", "Emilia", "Alexa", "Alinea", "Alina", "Leena", "Allyson", "Allison", "Alya", "Aliya", "Alys", "Alyce", "Ami", "Amee", "Andrea", "Aendrea", "Aria", "Arya", "Ariana", "Aryana", "Ariel", "Arielle", "Ashlene", "Ashlyne", "Aubree", "Aubria", "Bree", "Audree", "Audria", "Dree", "Aurora", "Ava", "Averee", "Avery", "Bella", "Brianna", "Brynn", "Bryanna", "Brooke", "Brooklyn", "Camila", "Clayre", "Clara", "Clayra", "Claire", "Cloe", "Cloey", "Delyla", "Dalia", "Eliana", "Elyna", "Liana", "Lyana", "Ella", "Ellie", "Elli", "Elyssa", "Lyssie", "Emma", "Eva", "Evylen", "Faline", "Genesys", "Jenessa", "Gina", "Ginna", "Janna", "Grayce", "Grace", "Halia", "Halie", "Hanna", "Hannah", "Harper", "Peria", "Hazel", "Azalea", "Isabel", "Belle", "Jasmine", "Jocelyn", "Joyce", "Celyne", "Kaeli", "Kathryn", "Kathrinn", "Cathryn", "Kayla", "Kym", "Kymber", "Layla", "Laila", "Lanna", "Lea", "Leia", "Leah", "Lily", "Lyly", "Lisbeth", "Lysbeth", "Luna", "Loona", "Madisyn", "Maya", "Maia", "Mea", "Melania", "Melany", "Mena", "Mina", "Mila", "Myla", "Milly", "Amelia", "Naomi", "Nataly", "Natta", "Natylie", "Natty", "Nycole", "Nicolle", "Olyva", "Alivia", "Olivia", "Penelope", "Penny", "Rianna", "Ryanna", "Ruby", "Ryla", "Rilie", "Rylie", "Samitha", "Samentha", "Sara", "Sarah", "Savanna", "Scarlet", "Sharlotte", "Carlotta", "Sophia", "Stelly", "Stella", "Vala", "Valentyna", "Valea", "Valerya", "Valerie", "Victoria", "Victora", "Violet", "Viola", "Zoe", "Zoey", "Zosy")
  fem3 <- c("Abryia", "Abrjia", "Bryia", "Brjia", "Abyiga", "Abjiga", "Adryia", "Adrjia", "Dryia", "Drjia", "Aleksa", "Alisya", "Alisja", "Aliya", "Alija", "Alysann", "Alisann", "Alyss", "Aliss", "Amya", "Amja", "Andreya", "Andreja", "Anika", "Arya", "Arja", "Aryana", "Arjana", "Aryel", "Arjel", "Aslyena", "Asljena", "Bela", "Brooka", "Bruka", "Brynn", "Brinn", "Dalilja", "Dalilya", "Elisabet", "Ellya", "Ellja", "Elyana", "Eljana", "Ema", "Emili", "Amilja", "Eva", "Eva", "Falyne", "Faline", "Feryia", "Ferjia", "Graya", "Graja", "Halya", "Halja", "Hanna", "Hazel", "Isabel", "Ysabel", "Jenesa", "Yenesa", "Kalya", "Kalja", "Kamilia", "Kamilja", "Karlata", "Sharla", "Katrina", "Katya", "Katja", "Kayla", "Kaila", "Klara", "Kloya", "Kloja", "Kyma", "Kima", "Lana", "Leya", "Leja", "Lilja", "Lilya", "Lina", "Lyna", "Alyna", "Lippi", "Pippi", "Loona", "Lona", "Madyisa", "Madjisa", "Maya", "Maja", "Melanya", "Melanja", "Lanya", "Lanja", "Milya", "Milja", "Miya", "Mija", "Myla", "Mjila", "Natalya", "Natalja", "Natya", "Natja", "Nikola", "Olifya", "Olifja", "Oyara", "Ojara", "Perja", "Perya", "Ruby", "Rubi", "Ryanna", "Rjanna", "Ryila", "Rjila", "Samitya", "Samitja", "Sara", "Selyne", "Seline", "Skarlya", "Skarlja", "Sofi", "Sosya", "Sosja", "Soya", "Soja", "Tella", "Tylla", "Valentina", "Valerya", "Valerja", "Valya", "Valja", "Vanna", "Viktorya", "Viktorja", "Vila", "Vyla", "Yanna", "Janna", "Yasmine", "Jasmine", "Yella", "Jella", "Yemina", "Jemina", "Yvelyn", "Iveljin")
  fem4 <- c("Abigala", "Abia", "Abria", "Abressa", "Adria", "Adressa", "Alessa", "Alessana", "Alia", "Alya", "Alina", "Alinea", "Alinia", "Alisea", "Alisia", "Alissa", "Lyssa", "Alova", "Elva", "Amia", "Amya", "Amilia", "Andrea", "Ondrea", "Aria", "Ariana", "Ariella", "Aryella", "Aslena", "Azlena", "Avelia", "Avelina", "Averra", "Ferra", "Avia", "Azelia", "Hazelia", "Bella", "Bera", "Kimbera", "Brianna", "Brinna", "Brocalina", "Brokalina", "Calia", "Caliana", "Calla", "Camilia", "Carlotta", "Catrina", "Catherina", "Clara", "Claira", "Cloia", "Delia", "Delila", "Delyla", "Elia", "Ellya", "Eliana", "Ema", "Estella", "Estelia", "Eva", "Falinia", "Gianesia", "Genesia", "Gianna", "Gianna", "Grassia", "Grazia", "Halia", "Hanna", "Iasmina", "Jazmina", "Illa", "Ella", "Imina", "Isabella", "Laila", "Lailana", "Leia", "Lilia", "Lisabeta", "Betta", "Luna", "Madisinia", "Madizinia", "Maia", "Maya", "Melania", "Milannia", "Mia", "Mila", "Milia", "Natalia", "Natalya", "Nicola", "Nikola", "Nomi", "Nomia", "Oiara", "Oyara", "Pera", "Pinna", "Pia", "Pinelopi", "Riana", "Rilia", "Rubia", "Samena", "Samitia", "Sara", "Sarra", "Scarlotta", "Selina", "Jocelina", "Sofia", "Zofia", "Talia", "Talea", "Talya", "Valentina", "Fantina", "Valeria", "Feria", "Valia", "Vanna", "Fanna", "Viola", "Violetta", "Vittoria", "Vittora", "Zoia", "Uzoia", "Zosia", "Zusia") 
  
  fem_names <- sort(unique(c(fem1, fem2, fem3, fem4)))
  
  ## Masculine first names ----
              masc1 <- c("Aaryn", "Aaro", "Aarus", "Abramus", "Abrahm", "Abyl", "Abelus", "Adannius", "Adanno", "Aedam", "Adym", "Adamus", "Aedrian", "Aedrio", "Aedyn", "Aidyn", "Aelijah", "Elyjah", "Aendro", "Androe", "Aenry", "Hynroe", "Hynrus", "Aethan", "Aethyn", "Aevan", "Evyn", "Evanus", "Alecks", "Alyx", "Alexandyr", "Xandyr", "Alyn", "Alaen", "Andrus", "Aendrus", "Anglo", "Aenglo", "Anglus", "Antony", "Antonyr", "Astyn", "Astinus", "Axelus", "Axyl", "Benjamyn", "Benjamyr", "Braidyn", "Brydus", "Braddeus", "Brandyn", "Braendyn", "Bryus", "Bryne", "Bryn", "Branus", "Caeleb", "Caelyb", "Caerlos", "Carlus", "Cameryn", "Camerus", "Cartus", "Caertero", "Charlus", "Chaerles", "Chyrles", "Christophyr", "Christo", "Chrystian", "Chrystan", "Connorus", "Connyr", "Daemian", "Damyan", "Daenyel", "Danyel", "Davyd", "Daevo", "Dominac", "Dylaen", "Dylus", "Elius", "Aeli", "Elyas", "Helius", "Helian", "Emilyan", "Emilanus", "Emmanus", "Emynwell", "Ericus", "Eryc", "Eryck", "Ezekius", "Zeckus", "Ezekio", "Ezrus", "Yzra", "Gabrael", "Gaebriel", "Gael", "Gayl", "Gayel", "Gaeus", "Gavyn", "Gaevyn", "Goshwa", "Joshoe", "Graysus", "Graysen", "Gwann", "Ewan", "Gwyllam", "Gwyllem", "Haddeus", "Hudsyn", "Haesoe", "Haesys", "Haesus", "Handus", "Handyr", "Hantus", "Huntyr", "Haroldus", "Haryld", "Horgus", "Horus", "Horys", "Horyce", "Hosea", "Hosius", "Iaen", "Yan", "Ianus", "Ivaen", "Yvan", "Jaecoby", "Jaecob", "Jaeden", "Jaedyn", "Jaeremiah", "Jeremus", "Jasyn", "Jaesen", "Jaxon", "Jaxyn", "Jaxus", "Johnus", "Jonus", "Jonaeth", "Jonathyn", "Jordus", "Jordyn", "Josaeth", "Josephus", "Josaeus", "Josayah", "Jovanus", "Giovan", "Julyan", "Julyo", "Jyck", "Jaeck", "Jacus", "Kaevin", "Kevyn", "Vinkus", "Laevi", "Levy", "Levius", "Landyn", "Laendus", "Leo", "Leonus", "Leonaerdo", "Leonyrdo", "Lynardus", "Lincon", "Lyncon", "Linconus", "Logaen", "Logus", "Louis", "Lucius", "Lucae", "Lucaen", "Lucaes", "Lucoe", "Lucus", "Lyam", "Maeson", "Masyn", "Maetho", "Mathoe", "Matteus", "Matto", "Maxus", "Maximus", "Maximo", "Maxymer", "Mychael", "Mygwell", "Miglus", "Mythro", "Mithrus", "Naemo", "Naethyn", "Nathanus", "Naethynel", "Nicholaes", "Nycholas", "Nicholys", "Nicolus", "Nolyn", "Nolanus", "Olivyr", "Alivyr", "Olivus", "Oscarus", "Oscoe", "Raen", "Ryn", "Robertus", "Robett", "Bertus", "Romyn", "Romanus", "Ryderus", "Ridyr", "Samwell", "Saemuel", "Santegus", "Santaegus", "Sybasten", "Bastyen", "Tago", "Aemo", "Tagus", "Theodorus", "Theodus", "Thaeodore", "Thomys", "Thomas", "Tommus", "Tylus", "Tilyr", "Uwyn", "Oewyn", "Victor", "Victyr", "Victorus", "Vincynt", "Vyncent", "Vincentus", "Wyttus", "Wyaett", "Xavius", "Havius", "Xavyer", "Yago", "Tyago", "Tyego", "Ysaac", "Aisaac", "Ysaiah", "Aisiah", "Siahus", "Zacharus", "Zachar", "Zachaery")
            masc2 <- c("Aaron", "Aaryn", "Abram", "Bram", "Abyl", "Abel", "Adam", "Aedam", "Adrian", "Hadrian", "Aiden", "Aidyn", "Alyx", "Alix", "Andres", "Andrew", "Andre", "Angel", "Anthony", "Astin", "Axel", "Axyl", "Benjamyn", "Benjamin", "Braddeus", "Bradyn", "Brynden", "Brandyn", "Bryne", "Bryan", "Bran", "Calyb", "Caleb", "Camryn", "Cam", "Carliss", "Cartyr", "Cartus", "Chirles", "Charly", "Conner", "Cristian", "Crystan", "Damien", "Damyn", "Daniel", "Dannel", "Dann", "Danny", "David", "Davyd", "Diegon", "Tiagon", "Domnac", "Dylan", "Eli", "Ely", "Elias", "Elyas", "Elijah", "Elijan", "Emilian", "Emynwell", "Emmyn", "Emmon", "Eric", "Eryc", "Ethan", "Athyn", "Evan", "Evyn", "Ezran", "Ezrus", "Gabreil", "Gabreal", "Gael", "Gayl", "Gavyn", "Gavin", "Gray", "Grasyn", "Haddeus", "Hudsen", "Handyr", "Hander", "Harold", "Haryld", "Horus", "Horace", "Horyce", "Hoseas", "Huntyr", "Han", "Hynry", "Henro", "Iaen", "Ian", "Isaac", "Isiah", "Isaias", "Ivaen", "Ivan", "Jacoby", "Jacob", "Jaeden", "Jayden", "Jak", "Jyck", "Jasyn", "Jason", "Jax", "Jaxon", "Jaymes", "Iamus", "Jestin", "Yestin", "John", "Jonn", "Jonath", "Joathyn", "Jorden", "Jordyn", "Joseth", "Joeseph", "Joshen", "Goshen", "Josyah", "Josius", "Jovan", "Julian", "Julyan", "Kevin", "Kevan", "Lan", "Alyn", "Landon", "Landyn", "Lenus", "Linus", "Leon", "Leo", "Lynard", "Levi", "Levy", "Liam", "Logan", "Lucan", "Luc", "Lucas", "Lucyus", "Louis", "Lyncon", "Lincus", "Mason", "Masyn", "Mathew", "Mattius", "Matt", "Maximer", "Maximus", "Michael", "Migwell", "Mither", "Nathyn", "Nathan", "Nathynel", "Nathanyel", "Nicholus", "Nik", "Noam", "Nolyn", "Nolan", "Olver", "Olliver", "Osco", "Oscus", "Oscar", "Owyn", "Owen", "Remus", "Jaeremy", "Rian", "Ryan", "Robett", "Robb", "Roman", "Romyn", "Ryder", "Samwell", "Samuel", "Sebasten", "Bastien", "Taegus", "Santus", "Theodor", "Theodus", "Thedoras", "Thomys", "Tommas", "Tomm", "Thom", "Tophyr", "Cristor", "Tylor", "Ty", "Tylus", "Victor", "Vyctor", "Vincent", "Vyncent", "Vynce", "Wann", "Wanny", "Willam", "Willem", "Wytt", "Xander", "Alexander", "Xavyer", "Xavy", "Havy", "Zachaery", "Zeke", "Zeek", "Ezekyel")  
            
            masc3 <- c("Aaro", "Aaryn", "Abel", "Adryan", "Adrjan", "Adym", "Adam", "Aksel", "Aleks", "Aleksander", "Alver", "Andrey", "Andrej", "Andrus", "Anton", "Anyel", "Anjel", "Astyn", "Asten", "Aydyn", "Ayden", "Benyen", "Benjen", "Brahm", "Brahn", "Brandyn", "Brandjen", "Branus", "Bronn", "Dain", "Davek", "Dale", "Damyin", "Damjin", "Dan", "Danyel", "Danjel", "Domnik", "Efan", "Efjan", "Efyan", "Elijan", "Eliyan", "Elje", "Elye", "Emanus", "Emilyan", "Emiljan", "Eryk", "Erik", "Esran", "Ethyn", "Gabrjel", "Gabryel", "Gafyn", "Gafjen", "Gayl", "Gail", "Graysen", "Graisen", "Hadsen", "Hudsen", "Hafyus", "Hafjus", "Han", "Handus", "Harold", "Helyan", "Heljan", "Henrik", "Horgus", "Hossen", "Ifjan", "Yfan", "Jak", "Yak", "Jakob", "Yakob", "Jamye", "Jamje", "Jan", "Yak", "Jasyn", "Jasjen", "Johan", "Yohan", "Joren", "Yoren", "Josef", "Yosef", "Julyan", "Juljan", "Yulian", "Kaliv", "Kamrus", "Kanus", "Karl", "Yarl", "Jarl", "Karlus", "Kartus", "Kefyan", "Kefjan", "Kristofer", "Tofer", "Kristyan", "Kristjan", "Lan", "Landen", "Lefi", "Lokan", "Lucyus", "Lucjius", "Lukas", "Lyam", "Ljam", "Lyenard", "Ljenard", "Lynkus", "Linkus", "Lyonus", "Ljonus", "Lyuk", "Ljuk", "Maks", "Masyn", "Matye", "Matje", "Matyus", "Matjus", "Miglus", "Mitye", "Mitje", "Mykael", "Natyan", "Natjan", "Natyanus", "Natjanus", "Nikolas", "Nolen", "Nom", "Oskar", "Owyn", "Ojin", "Remus", "Robyet", "Robjet", "Romyn", "Romen", "Ryderus", "Riderus", "Ryn", "Rjan", "Sammen", "Santyeg", "Santjeg", "Sebastyan", "Sebastjan", "Sekyus", "Sekjus", "Skarye", "Skarje", "Teodus", "Teddus", "Tomus", "Tylus", "Tilus", "Viktor", "Viktus", "Vintus", "Vyntus", "Wilhelm", "Wyat", "Wjat", "Yaden", "Jaden", "Yaks", "Jaks", "Yaksen", "Jaksen", "Yesten", "Jesten", "Ygan", "Egan", "Yofan", "Jofan", "Yonaf", "Jonaf", "Yoshen", "Joshen", "Yosyen", "Josjen", "Ysak", "Isak", "Isaak", "Ysiah", "Isjah", "Isajas")
            masc4 <- c("Abelan", "Abbos", "Abramo", "Brammos", "Adamo", "Adamos", "Adrio", "Adrios", "Adros", "Aido", "Aidos", "Aleno", "Alennos", "Alessandro", "Alesso", "Alonso", "Alonnos", "Alvero", "Alvan", "Andoran", "Handros", "Andrean", "Andrenas", "Andro", "Andros", "Angelo", "Anglos", "Antonio", "Antono", "Aro", "Aros", "Astono", "Stonnos", "Benemo", "Benemos", "Brado", "Bridos", "Brando", "Brannos", "Bruno", "Bronnos", "Caliban", "Callos", "Camero", "Kamros", "Carlos", "Karlos", "Carolan", "Karolos", "Cartero", "Karros", "Cavo", "Cavos", "Conoro", "Konoros", "Cristeno", "Cristenos", "Cristofo", "Cristos", "Dalio", "Dalian", "Damino", "Dammos", "Danello", "Danellos", "Dano", "Dannos", "Davo", "Davios", "Domino", "Domnos", "Elian", "Helian", "Eligio", "Elihios", "Elio", "Ellios", "Emanolo", "Emannos", "Enrico", "Enrikos", "Esekio", "Esekios", "Esro", "Ezro", "Ezros", "Etan", "Evanio", "Ephanos", "Gabrilo", "Gabrios", "Galan", "Gallos", "Gavano", "Gavannos", "Giaco", "Jakos", "Giacomo", "Jacomo", "Jakomos", "Giadeo", "Hadeos", "Giasson", "Giassonos", "Gionato", "Gionatos", "Giorran", "Jorros", "Gioseno", "Giosenos", "Gioseppi", "Gioseppos", "Giosso", "Hossos", "Giovan", "Jovos", "Giulio", "Hulios", "Grassio", "Grassos", "Guan", "Jannos", "Guliemo", "Guliemos", "Haddeo", "Haddeos", "Hano", "Hanos", "Hanro", "Hanros", "Hanto", "Hantos", "Hasselo", "Axlos", "Havio", "Xavios", "Horacio", "Horace", "Hosso", "Hossos", "Iacono", "Jakonos", "Iago", "Tiago", "Iamos", "Ianio", "Jannos", "Iasono", "Jasonos", "Iesso", "Hessos", "Iono", "Yonnos", "Isamo", "Isamos", "Isimo", "Isimos", "Ivano", "Ibannos", "Jeraldo", "Graddos", "Lando", "Landos", "Leo", "Leon", "Leon", "Leonnos", "Levio", "Lebbios", "Liamo", "Liamos", "Lincono", "Linconos", "Lucios", "Lukios", "Luco", "Lucos", "Lugo", "Lucan", "Luho", "Luhos", "Masono", "Masnos", "Massimo", "Maksimos", "Mateo", "Mateos", "Matos", "Matto", "Mattos", "Miglan", "Miglos", "Miguel", "Miguelos", "Milio", "Miliano", "Milyannos", "Mitro", "Mitros", "Natan", "Natannos", "Nateo", "Natos", "Nicolo", "Nicos", "Nolano", "Nolannos", "Oscaro", "Oskos", "Otio", "Ottios", "Remo", "Remmos", "Riano", "Rianos", "Ridero", "Riddros", "Robero", "Robbos", "Roman", "Romannos", "Saccoro", "Saccaros", "Samual", "Samos", "Santo", "Santos", "Sebastio", "Sebastos", "Bastio", "Teodoro", "Theodorus", "Tiago", "Iago", "Iagos", "Tagos", "Tilo", "Tiloros", "Tomo", "Tommos", "Uenio", "Unnos", "Victoran", "Tornos", "Vincenso", "Vincenzo", "Vinnos")   
            
            
            # Surnames -----
            sur1 <- c("Bright", "Brown", "Browne", "Brushfire", "Camp", "Campman", "Canyon", "Cricketts", "Crickets", "Dunes", "Doons", "Doones", "Dunne", "Dunneman", "Flats", "Fox", "Foxx", "Gold", "Golden", "Grey", "Gray", "Gulch", "Gully", "Hardy", "Hills", "Hill", "Hopper", "Hunter", "Huntsman", "March", "Marcher", "Moon", "Redmoon", "Palmer", "Palms", "Peartree", "Pearman", "Redd", "Red", "Rider", "Ryder", "Rock", "Rockman", "Rock", "Rockman", "Rocker", "Sands", "Scales", "Redscale", "Greyscale", "Singer", "Small", "Smalls", "Star", "Starr", "Stone", "Stoneman", "Storm", "Storms", "Strider", "Stryder", "Sunn", "Sunner", "Tumbleweed", "Walker", "Water", "Watters")
            sur2 <- c("Appletree", "Appler", "Applin", "Barley", "Barleycorn", "Barleywine", "Barns", "Barnes", "Barnard", "Beans", "Beanman", "Beanstalk", "Berry", "Berryland", "Bloom", "Bloomland", "Brown", "Brownland", "Brownard", "Bull", "Bullyard", "Cabbage", "Kabbage", "Cotton", "Cottonseed", "Croppe", "Cropman", "Dairyman", "Darryman", "Darry", "Derry", "Farmer", "Farmor", "Fields", "Fielder", "Fieldman", "Flats", "Redflats", "Sandflats", "Stoneflats", "Flowers", "Gardner", "Gardener", "Gardiner", "Green", "Greene", "Greenland", "Greenyard", "Grove", "Groveland", "Hays", "Hayes", "Hayward", "Henkeeper", "Hennerman", "Herd", "Hurd", "Herdland", "Land", "Lander", "Mares", "Mayr", "Mair", "Meadows", "Milk", "Millet", "Millett", "Mills", "Miller", "Millard", "Neeps", "Neepland", "Nutt", "Nutman", "Oates", "Oats", "Overland", "Overfield", "Peartree", "Pearman", "Pease", "Peapod", "Peabody", "Picket", "Picketts", "Pickens", "Pickman", "Plant", "Planter", "Ploughman", "Plowman", "Plougherman", "Pollen", "Pollin", "Polly", "Pollard", "Rains", "Raines", "Rayns", "Raynes", "Rainard", "Root", "Roote", "Rutland", "Shepherd", "Shepard", "Shepyrd", "Shearer", "Sheerer", "Shears", "Sheers", "Sower", "Soward", "Tate", "Tater", "Thresh", "Threshett", "Tiller", "Tillman", "Vines", "Vineland", "Wheatley", "Wheatly", "Wheat", "Whittaker", "Whitard", "Winnows", "Winnower", "Wool", "Woolard", "Yardly", "Yardley", "Yards")  
            sur3 <- c("Ales", "Aleman", "Aler", "Baker", "Bake", "Bakeler", "Barr", "Barre", "Barman", "Berry", "Berryman", "Berriman", "Boyle", "Boiles", "Boyles", "Brewer", "Brewster", "Broyles", "Broiles", "Broyler", "Butcher", "Butchett", "Cook", "Dice", "Dougherman", "Dougher", "Fry", "Frey", "Fryman", "Gardner", "Gardener", "Gardiner", "Grills", "Grillett", "Innes", "Innman", "Inman", "Kettle", "Kettleblack", "Kettleman", "Kneadler", "Kneadman", "Milk", "Miller", "Mills", "Miller", "Palewine", "Pan", "Pannerman", "Panning", "Peppers", "Pepper", "Pickler", "Pickleman", "Pickles", "Pieman", "Piemaker", "Potts", "Pott", "Potter", "Redwine", "Roasterman", "Salt", "Salter", "Simms", "Simmerman", "Slaughter", "Smoke", "Smoker", "Vines", "Vintner", "Vinaker Winaker", "Wineman")  
            sur4 <- c("Biggs", "Bigg", "Byggs", "Camp", "Campman", "Coates", "Frost", "Furrs", "Furrman", "Graysky", "Whitesky", "Blacksky", "Grey", "Gray", "Hardy", "Hardison", "Hardland", "Harland", "Hills", "Hill", "Hylls", "Hunter", "Huntsman", "Ice", "Iceland", "Icewind", "Icecutter", "Yceland", "Ycewind", "Ycecutter", "Longnight", "Longdark", "Moon", "Wintermoon", "North", "Northman", "Norman", "Northland", "Norland", "Pix", "Pickman", "Pickes", "Pyckes", "Seales", "Seals", "Silver", "Silvermoon", "Sylver", "Snow", "Snowes", "Star", "Starr", "Northstar", "Stone", "Stoneman", "Strider", "Stryder", "Walker", "White", "Whyte", "Winter", "Winters", "Wynters")  
            sur5 <- c("Bobbin", "Bolt", "Bolte", "Bolter", "Button", "Buttonworth", "Capers", "Coates", "Cotton", "Dyer", "Dye", "Dyeworth", "Dyerson", "Dyson", "Felter", "Felterman", "Glover", "Hatter", "Hatty", "Hattiman", "Hatson", "Hemmings", "Hemings", "Hemson", "Hyde", "Hides", "Hydes", "Leathers", "Lethers", "Mercer", "Needleman", "Needler", "Needleworth", "Seams", "Seems", "Seemworth", "Shearer", "Sheerer", "Shears", "Sheers", "Shoemaker", "Stitches", "Stitchworth", "Tailor", "Taylor", "Tanner", "Tannerman", "Thredd", "Threddler", "Threddman", "Threddaker", "Weaver", "Weever", "Wool", "Woolworth", "Yardly", "Yardley", "Yards")  
            sur6 <- c("Bay", "Bayes", "Bayer", "Bayers", "Beacher", "Beach", "Blue", "Bowman", "Castaway", "Crabb", "Crab", "Crest", "Days", "Dayes", "Dunes", "Doons", "Doones", "Dunne", "Dunneman", "Eddy", "Fisher", "Fishman", "Flowers", "Harper", "Hook", "Hooke", "Iles", "Isles", "Ailes", "Mast", "Palmer", "Palms", "Rafman", "Raftman", "Reel", "Reelings", "Salt", "Seasalt", "Sands", "Sandman", "Seabreeze", "Shell", "Shellman", "Shellmound", "Sheller", "Shelley", "Shoals", "Singer", "Star", "Starr", "Stern", "Sterne", "Stillwater", "Storm", "Storms", "Summers", "Sunn", "Sunner", "Swimmer", "Shwimmer", "Swymmer", "Tidewater", "Waters", "Watters", "Waterman")  
            sur7 <- c("Arch", "Archmaker", "Baskett", "Basket", "Bilder", "Builder", "Bulder", "Bilds", "Blow", "Brickman", "Bricker", "Brycks", "Bricks", "Burgh", "Berg", "Burg", "Burgher", "Berger", "Burger", "Carpenter", "Chandler", "Candler", "Clay", "Cooper", "Crafter", "Glass", "Glazier", "Glasier", "Hammer", "Maker", "Mason", "Masen", "Masyn", "Potts", "Pott", "Potter", "Quarrier", "Quarryman", "Rock", "Rockman", "Rocker", "Roof", "Roofe", "Sawyer", "Stone", "Stoneman", "Townes", "Towns", "Towny", "Wahl", "Wall", "Wahls", "Walls", "Waller", "Waxman", "Wax", "Wackes", "Wood", "Woods")
            sur8 <- c("Billy", "Billie", "Bluffe", "Bluffclimber", "Boulder", "Bulder", "Camp", "Campman", "Claymer", "Clayms", "Claimer", "Cole", "Coler", "Coleman", "Coalman", "Coaler", "Coaldigger", "Coledegger", "Condor", "Condorman", "Cragg", "Cragman", "Diggs", "Digger", "Diggman", "Digger", "Diggett", "Dragonhoard", "Dragonhord", "Dragon", "Drake", "Dredge", "Dredger", "Hall", "Haul", "Heights", "Hights", "Hytes", "Hites", "Highland", "Hills", "Hill", "Hillclimber", "Hylltopper", "Hoard", "Hord", "Hoar", "Hoardigger", "Hordegger", "Kidd", "Kipman", "Kipper", "Kipson", "Kopperfield", "Miner", "Myner", "Mynor", "Minor", "Mole", "Moler", "Moller", "Molson", "Molsen", "Ores", "Orr", "Orrs", "Oredigger", "Orrdegger", "Orson", "Orrsen", "Pan", "Pans", "Pannerman", "Panning", "Peaks", "Peeks", "Pike", "Pyke", "Pikeclimber", "Pyketopper", "Pix", "Pickman", "Pickes", "Pyckes", "Pickens", "Quarrier", "Quarryman", "Ridge", "Ridgeclimber", "Ridgetopper", "Rock", "Rockman", "Rocker", "Rockridge", "Snow", "Snowes", "Spade", "Spader Springs", "Springer", "Stone", "Stoneman", "Underhill", "Underwood", "Underman", "Walker")  
            sur9 <- c("Barr", "Barre", "Cash", "Copper", "Coppers", "Curry", "Deals", "Deels", "Deel", "Deelaker", "Deelman. Diamond", "Glass", "Glazier", "Glasier", "Gold", "Golden", "Goldsmith", "Goldman", "Jewels", "Jules", "Jewls", "Lender", "Lenderman", "Lynder", "Mercer", "Money", "Munny", "Monny", "Munnee", "Monnee", "Peppers", "Pepper", "Rich", "Richman", "Richett", "Riches", "Saffron", "Sage", "Salt", "Scales", "Shine", "Ships", "Schipps", "Shipps", "Shipman", "Schippman", "Silver", "Sylver", "Silverman", "Small", "Smalls", "Spicer", "Spiceman", "Star", "Starr", "Thyme", "Ware", "Wool")
            sur10 <- c("Altarside", "Altarworthy", "Beacon", "Beecon", "Beeken", "Bell", "Bolt", "Bolte", "Bolter", "Bones", "Bright", "Burns", "Cast", "Caster", "Kast", "Chaplain", "Chaplin", "Church", "Churchside", "Darko", "Darkstar", "Darker", "Darkbrother", "Deacon", "Deecon", "Deeken", "Drake", "Draco", "Dragon", "Dreamer", "Dreemer", "Dreems", "Goodbrother", "Goodman", "Hecks", "Heckes", "Hex", "Holiday", "Holliday", "Holyday", "Hollier", "Holly", "Holier", "Hollison", "Hood", "Kearse", "Kerse", "Kerser", "Curser", "Monk", "Munk", "Nunn", "Nun", "Powers", "Preacher", "Preecher", "Priest", "Preest", "Sage", "Sageworthy", "Saint", "School", "Skool", "Skolar", "Scholyr", "Shock", "Shocker", "Shaka", "Skelton", "Skeltyn", "Smart", "Spelling", "Speller", "Star", "Starr", "Brightstar", "Teech", "Teeches", "Theery", "Tinker", "Tutor", "Tudor", "Vickers", "Vykar", "Vicker", "Vikars", "Wise", "Overwise", "Worthy", "Zapp", "Zappa")   
            sur11 <- c("Banks", "Bankes", "Bend", "Benderman", "Blue", "Bridges", "Cray", "Craw", "Eddy", "Ferryman", "Ferrimen", "Ferry", "Fisher", "Fishman", "Flowers", "Garr", "Hook", "Hooke", "Hopper", "Iles", "Isles", "Ailes", "Mills", "Miller", "Oars", "Orrs", "Orr", "Oxbow", "Piers", "Peers", "Poleman", "Polman", "Porter", "Rafman", "Raftman", "Reed", "Reede", "Reedy", "Reel", "Reelings", "River", "Rivers", "Salmon", "Shell", "Shellman", "Sheller", "Shelley", "Silver", "Silvermoon", "Small", "Smalls", "Snails", "Snailman", "Spanner", "Stillwater", "Streams", "Streems", "Swimmer", "Shwimmer", "Swymmer", "Trout", "Waters", "Watters", "Waterman", "Whitewater", "Wurms", "Worms")
            sur12 <- c("Anchor", "Ankor", "Anker", "Ballast", "Bay", "Bayes", "Bayer", "Bayers", "Beacon", "Biggs", "Bigg", "Brigg", "Briggs", "Bowman", "Capp", "Capman", "Castaway", "Crabb", "Crab", "Crabber", "Crabman", "Crest", "Darkwater", "Decks", "Decker", "Eddy", "Ferryman", "Ferrimen", "Ferry", "Fisher", "Fishman", "Hardy", "Hardison", "Harper", "Helms", "Helmsman", "Hook", "Hooke", "Iles", "Isles", "Ailes", "Mast", "Oars", "Orrs", "Orr", "Piers", "Peers", "Pitch", "Pytch", "Porter Redtide", "Blacktide", "Riggs", "Riggett", "Sailor", "Saylor", "Sailer", "Sayler", "Salt", "Seasalt", "Saltman", "Seabreeze", "Seaman", "Season", "Seeman", "Ships", "Schipps", "Shipps", "Shipman", "Schippman", "Shore", "Shoreman", "Singer", "Star", "Starr", "Stern", "Sterne", "Storm", "Storms", "Swimmer", "Shwimmer", "Swymmer", "Tar", "Tarr", "Tidewater", "Tuggs", "Tugman", "Waters", "Watters", "Waterman", "Whitewater")
            sur13 <- c("Anvill", "Anvilson", "Bellows", "Black", "Blackiron", "Copper", "Coppers", "Farrier", "Fletcher", "Fletchett", "Forger", "Forgeman", "Goldsmith", "Grey", "Greysteel", "Hammer", "Hammett", "Irons", "Yrons", "Ironsmith", "Ironshoe", "Ironhoof", "Kettle", "Kettleblack", "Kettleman", "Potts", "Pott", "Pottaker", "Pound", "Poundstone", "Shields", "Shieldson", "Slagg", "Slagman", "Smith", "Smyth", "Smitts", "Smittens", "Smitty", "Smythett", "Smoke", "Smoker", "Steel", "Steele", "Steelman", "Swords", "Swordson", "Tinn", "Tinman", "Tynn", "Tyne", "Tine")
            sur14 <- c("Ackes", "Ax", "Archer", "Bailey", "Banner", "Bannerman", "Bay", "Bayes", "Bones", "Boots", "Bootes", "Bowman", "Chestnut", "Colt", "Colter", "Dice", "Dyce", "Dycen", "Dyson", "Flagg", "Flag", "Helms", "Hightower", "Knight", "Leathers", "Lethers", "March", "Marcher", "Mares", "Mayr", "Mair", "Marks", "Mercer", "Pike", "Pikes", "Pyke", "Pykes", "Pikeman", "Pykeman", "Poleman", "Polman", "Rider", "Ryder", "Shields", "Shieldson", "Slaughter", "Spears", "Speers", "Swords", "Swordson", "Towers", "Wahl", "Wall", "Wahls", "Walls", "Waller")
            sur15 <- c("Bay", "Bayes", "Brand", "Carrier", "Carryer", "Carter", "Carton", "Cartwright", "Chestnut", "Colt", "Colter", "Driver", "Dryver", "Foote", "Handler", "Mares", "Mayr", "Mair", "Porter", "Quicke", "Quick", "Reines", "Reynes", "Reins", "Reyns", "Rider", "Ryder", "Ryde", "Saddler", "Stall", "Stalls", "Staller", "Stallworth", "Stallman", "Swift", "Swyft", "Trainor", "Trainer", "Wain", "Wayne", "Wayn", "Wainwright", "Waynwright")
            sur16 <- c("Banks", "Bankes", "Black", "Blacktide", "Greentide", "Boggs", "Bogg", "Bogs", "Bull", "Buzzfly", "Blackfly", "Shoefly", "Cray", "Craw", "Cricketts", "Crickets", "Darkwater", "Dragonfly", "Dragon", "Eeler", "Ealer", "Eeles", "Eales", "Fisher", "Fishman", "Frogg", "Frogman", "Green", "Greene", "Greenwater", "Blackwater", "Grey", "Gray", "Grove", "Groves", "Hook", "Hooke", "Hopper", "Marsh", "Mayfly", "May", "Moss", "Mosstree", "Greentree", "Poisonweed", "Poisonwood", "Polly", "Pollywog", "Polliwog", "Rafman", "Raftman", "Ratt", "Ratman", "Reed", "Reede", "Reedy", "River", "Rivers", "Rotten", "Rotman", "Scales", "Greenscale", "Blackscale", "Shell", "Shellman", "Sheller", "Shelley", "Skeeter", "Skito", "Small", "Smalls", "Snails", "Snailman", "Stillwater", "Swimmer", "Shwimmer", "Swymmer", "Thick", "Thicke", "Tidewater", "Vines", "Waters", "Watters", "Wurms", "Worms")
            sur17 <- c("Alley", "Allie", "Bailey", "Bell", "Berg", "Berger", "Burg", "Burger", "Brickman", "Brickhouse", "Bridges", "Court", "Gardner", "Gardiner", "Hall", "Heap", "Hightower", "Hood", "House", "Lane", "Lain", "Laine", "Lodge", "Lodges", "Park", "Parks", "Plaza", "Rhoads", "Rhodes", "Roades", "Roof", "Spanner", "Stairs", "Street", "Streets", "Towers", "Towns", "Townsend", "Townes", "Towny", "Towney", "Vista", "Wall", "Wahl", "Woodhouse")
            sur18 <- c("Ackes", "Ax", "Archer", "Berry", "Biggs", "Bigg", "Birch", "Byrch", "Bird", "Byrd", "Birdett", "Byrdman", "Bloom", "Bowman", "Branch", "Brush", "Buck", "Deere", "Deerman", "Doe", "Feller", "Fletcher", "Flowers", "Forester", "Forrester", "Forrest", "Fox", "Foxx", "Gardner", "Gardener", "Gardiner", "Green", "Greene", "Grove", "Groves", "Harper", "Hatchet", "Hunter", "Huntsman", "Hyde", "Hides", "Hydes", "Jack", "Lodge", "Lodges", "Meadows", "Mole", "Moler", "Moller", "Moss", "Mosstree", "Greentree", "Oaks", "Oakes", "Pine", "Pines", "Pyne", "Pynes", "Sawyer", "Silver", "Silvermoon", "Singer", "Springs", "Springer", "Strider", "Stryder", "Tanner", "Tannerman", "Thick", "Thicke", "Walker", "Woods", "Wood", "Woode", "Wooden", "Woodyn")
  
  # Make sure count is an integer
  npc_count <- round(x = npc_count, digits = 0)
  
  # Pick a race
  npc_race <- sample(x = dndR::dnd_races(), size = npc_count, replace = TRUE)
  
  # Pick a career
  npc_role <- sample(x = c("acolyte", "adventurer", "ambassador", "anthropologist", "archaeologist", "artisan", "barber", "bounty hunter", "caravan driver", "caravan guard", "carpenter", "charlatan", "city watch", "criminal", "diplomat", "doctor", "farmer", "farrier", "entertainer", "gladiator", "hermit", "initiate", "inquisitor", "investigator", "knight", "mercenary", "merchant", "navigator", "noble", "outlander", "sage", "scholar", "smith", "soldier", "spy", "student of magic", "smuggler", "urchin", "veteran"),
                     size = npc_count, replace = TRUE)
  
  # Assemble into named vector
  npc_info <- data.frame("race" = npc_race, 
                         "job" = npc_role)
  
  # Return the data.frame
  return(npc_info) }



# End ----
